# Generated by Django 3.1.1 on 2020-10-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdistributionaogs',
            name='officialDistribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AOGS_distributions', to='api.officialdistributionogs'),
        ),
    ]
