# Generated by Django 3.1.1 on 2020-10-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201010_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdistributionaogs',
            name='guardOfficerHelper',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.worker'),
        ),
        migrations.AlterField(
            model_name='officialdistributionaogs',
            name='officialDistribution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='AOGS_distributions', to='api.officialdistributionogs'),
        ),
    ]
