# Generated by Django 3.1.1 on 2020-10-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201010_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityseat',
            name='isOfficialDistributionOGSPublished',
            field=models.BooleanField(default=False),
        ),
    ]
